# Use the official PostgreSQL image from Docker Hub
FROM postgres:latest

# Environment variables
ENV POSTGRES_USER=dbadmin
ENV POSTGRES_PASSWORD=dbadmin
ENV POSTGRES_DB=fitness_tracker_db

# Expose PostgreSQL port
EXPOSE 5432
